FROM openjdk:latest
COPY target/todo-server-1.0-SNAPSHOT-jar-with-dependencies.jar todo-server-1.0-SNAPSHOT-jar-with-dependencies.jar
ENTRYPOINT ["java","-jar","/todo-server-1.0-SNAPSHOT-jar-with-dependencies.jar"]

