FROM openjdk:latest
COPY todo-server-1.0-SNAPSHOT-jar-with-dependencies,jar gRPC-practice-1.0-SNAPSHOT-jar-with-dependencies.jar
ENTRYPOINT ["java","-jar","target/gRPC-practice-1.0-SNAPSHOT-jar-with-dependencies.jar"]

