name:  graphql-grpc-poc CI/CD
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2
      - name: docker login to github container registry
        uses: docker/login-action/@v2
        with:
         registry: ${{ secrets.REGISTRY }}
         username: ${{ secrets.REGISTRY_USERNAME }}
         password: ${{ secrets.REGISTRY_TOKEN }}

  build_grpc:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: todo-server/
    steps:
      - name: clone repo
        uses: actions/checkout@v2
      - name: docker login to github container registry
        uses: docker/login-action/@v2
        with:
         registry: ${{ secrets.REGISTRY }}
         username: ${{ secrets.REGISTRY_USERNAME }}
         password: ${{ secrets.REGISTRY_TOKEN }}
      - name: install dependencies and run test cases
        run: mvn clean install
      - name: ls  
        run: |
         cd target 
         ls
      - name: build grpc-server
        run: docker build . -t ${{ secrets.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/todo-grpc-server:latest
      - name: docker push grpc-server
        run: docker push ${{ secrets.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/todo-grpc-server:latest
        
  build_graphql:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bff/
    steps:
      - name: clone repo
        uses: actions/checkout@v2
      - name: install dependencies
        run: npm install
      - name: docker login to github container registry
        uses: docker/login-action/@v2
        with:
         registry: ${{ secrets.REGISTRY }}
         username: ${{ secrets.REGISTRY_USERNAME }}
         password: ${{ secrets.REGISTRY_TOKEN }}
      - name: build graphql-client 
        run: docker build . -t ${{ secrets.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/todo-graphql-client:latest
      - name: docker graphql-client 
        run: docker push ${{ secrets.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/todo-graphql-client:latest
 
  build_frontend:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: todo-client/
    steps:
      - name: clone repo
        uses: actions/checkout@v2
      - name: docker login to github container registry
        uses: docker/login-action/@v2
        with:
         registry: ${{ secrets.REGISTRY }}
         username: ${{ secrets.REGISTRY_USERNAME }}
         password: ${{ secrets.REGISTRY_TOKEN }}
      - name: install dependencies
        run: npm install
      - name: docker build frontend
        run: docker build . -t ${{ secrets.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/todo-fe:latest 
      - name: docker push frontend
        run: docker push ${{ secrets.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/todo-fe:latest 
  
      